<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_FBIntegrator
 * @copyright  Copyright (c) 2003-2009 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<br />
<div class="page-head facebook">
<h3><?php //echo $this->__('Facebook user? Use a form below') ?>
<img src="<?php echo $this->getSkinUrl('images/axiadesign/02_inscription/btitle_facebok.gif') ?>"  />
</h3>	
</div>
<div class="col2-set login-box fbintegrator-login-box facebook">
    <div class="col-1 new-users">
    	<form id="fbintegrator-form">
        <div class="content">
            <h4 "><?php //echo $this->__('Fast sign up with Facebook') ?>
            <img src="<?php echo $this->getSkinUrl('images/axiadesign/02_inscription/title_enregface.gif') ?>"  /></h4>
            <p><?php echo $this->__('') ?></p>
            <ul class="form-list">
                <li>
                    <label for="username"><?php echo Mage::helper('customer')->__('Email Address') ?> <span class="required">*</span></label><br />
                    <input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" title="<?php echo $this->__('Email Address') ?>" id="username" type="text" class="input-text validate-email required-entry" style="width:250px;" />
                </li>
                <li>
                    <label for="password"><?php echo Mage::helper('customer')->__('Password') ?> <span class="required">*</span></label><br />
                    <input name="login[password]" type="password" class="input-text required-entry validate-password" id="password" style="width:250px;" />
                </li>
                <li>
                    <label for="confirmation"><?php echo Mage::helper('customer')->__('Confirm Password') ?> <span class="required">*</span></label><br />
                    <input name="login[confirmation]" type="password" class="input-text required-entry validate-cpassword" id="confirmation" style="width:250px;" />
                </li>
                <?php if ($this->isNewsletterEnabled()): ?>
                <li>
                    <input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" />
                    <label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
                </li>
                <?php endif ?>
            </ul>
            <p class="required"  style="margin-top:-179px;"><?php echo $this->__('* Required Fields') ?></p>
        </div>
        <div class="button-set">
        	<a href="#" onclick="fbiRegister(); return false;" class="right"> <img id="fb_login_image" src="<?php echo $this->getSkinUrl('images/axiadesign/02_inscription/bt_connecface_off.gif') ?>" alt="<?php echo $this->__('Register') ?>" /> </a>
            <span id="fbintegrator-register-loading" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/fbintegrator/ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading...') ?> &nbsp;
            </span>
        </div>
        </form>
    </div>
    <div class="col-2 registered-users facebook">
        <div class="content">
            <h4><?php //echo $this->__('Fast login with Facebook') ?>
            <img src="<?php echo $this->getSkinUrl('images/axiadesign/02_inscription/title_idface.gif') ?>"  /></h4>
            <p><?php echo $this->__('Have an account here and on Facebook? Click the button below to login.') ?></p>
        </div>
        <div class="button-set">
            <a href="#" onclick="fbiLogin(); return false;" class="right"> <img id="fb_login_image" src="<?php echo $this->getSkinUrl('images/axiadesign/02_inscription/bt_connecface_off.gif') ?>" alt="<?php echo $this->__('Login') ?>" /> </a>
            <span id="fbintegrator-login-loading" style="display:none;">
                <img src="<?php echo $this->getSkinUrl('images/fbintegrator/ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading...') ?> &nbsp;
            </span>
        </div>
    </div>
</div>
<div id="fbintegrator-overlay"></div>
<div id="fbintegrator">
	<div id="fbiContent"></div>
    <div id="fbiLoadMessage">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading...') ?>
    </div>
</div>



<script type="text/javascript">
fbiDomLoaded = false;

var FBLogin = new FBIntegratorLogin('<?php echo $this->getLoginFormUrl() ?>');
var Facebook = new FBIntegrator('<?php echo $this->getApiKey() ?>', '<?php echo $this->getXdUrl() ?>', '<?php echo $this->getAjaxUrl() ?>', FBLogin);
document.observe('dom:loaded', function () {fbiDomLoaded = true});
fbiRegister = function(){
	if (!fbiDomLoaded) return false;
	if ('undefined' != typeof(Facebook)){
		if (Facebook.validateForm($('fbintegrator-form'))){
			Facebook.ajaxLoader = $('fbintegrator-register-loading');
			Facebook.ajaxLoader.show();
			FB.Connect.requireSession(function() { Facebook.register($('fbintegrator-form')); });
		}
	}
};
fbiLogin = function(){
	if (!fbiDomLoaded) return false;
	if ('undefined' != typeof(Facebook)){
		Facebook.ajaxLoader = $('fbintegrator-login-loading');
		Facebook.ajaxLoader.show();
		FB.Connect.requireSession(function() { Facebook.login(); });
	}
};
</script>
